// Code generated by goctl. DO NOT EDIT.
// Source: usercenter.proto

package server

import (
	"context"

	"mxshop/app/usercenter/cmd/rpc/internal/logic/userservice"
	"mxshop/app/usercenter/cmd/rpc/internal/svc"
	"mxshop/app/usercenter/cmd/rpc/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServiceServer) SignOut(ctx context.Context, in *pb.SignOutReq) (*pb.SignOutResp, error) {
	l := userservicelogic.NewSignOutLogic(ctx, s.svcCtx)
	return l.SignOut(in)
}
